[WIP] include: Add support for C compilation
Joshua-Ashton/dxvk-native pull request #14
Opened 2022-03-11 18:53 UTC by flibitijibibo

This (mostly) fixes building FNA3D with dxvk-native... in exchange for totally breaking the actual dxvk build.

As a reminder, the FNA3D build:
```
git clone --recursive https://github.com/FNA-XNA/FNA3D
git clone https://github.com/Joshua-Ashton/dxvk-native
mkdir FNA3D/flibitBuild
cd FNA3D/flibitBuild
cmake .. -DBUILD_DXVK_NATIVE=ON
make
```

Test program (throw this in flibitBuild):
```
/* cc clear.c -I../include `sdl2-config --cflags --libs` libFNA3D.so */

#include <SDL.h>
#include <FNA3D.h>

int main(int argc, char **argv)
{
	SDL_Window *window;
	FNA3D_Device *device;
	FNA3D_PresentationParameters params;
	FNA3D_Vec4 color;
	SDL_Event evt;
	SDL_bool run = SDL_TRUE;

	SDL_Init(SDL_INIT_VIDEO);
	window = SDL_CreateWindow(
		"dxvk-native Test",
		SDL_WINDOWPOS_CENTERED,
		SDL_WINDOWPOS_CENTERED,
		640,
		480,
		SDL_WINDOW_SHOWN | FNA3D_PrepareWindowAttributes()
	);
	params.backBufferWidth = 640;
	params.backBufferHeight = 480;
	params.backBufferFormat = FNA3D_SURFACEFORMAT_COLOR;
	params.multiSampleCount = 0;
	params.deviceWindowHandle = window;
	params.isFullScreen = 0;
	params.depthStencilFormat = FNA3D_DEPTHFORMAT_NONE;
	params.presentationInterval = FNA3D_PRESENTINTERVAL_DEFAULT;
	params.displayOrientation = FNA3D_DISPLAYORIENTATION_DEFAULT;
	params.renderTargetUsage = FNA3D_RENDERTARGETUSAGE_DISCARDCONTENTS;
	device = FNA3D_CreateDevice(&params, 0);
	color.x = 1.0f;
	color.y = 0.0f;
	color.z = 0.0f;
	color.w = 0.0f;

	while (run)
	{
		while (SDL_PollEvent(&evt) > 0)
		{
			if (evt.type == SDL_QUIT)
			{
				run = SDL_FALSE;
			}
		}

		FNA3D_Clear(
			device,
			FNA3D_CLEAROPTIONS_TARGET,
			&color,
			1.0f,
			0
		);
		FNA3D_SwapBuffers(device, NULL, NULL, window);
	}

	FNA3D_DestroyDevice(device);
	SDL_DestroyWindow(window);
	SDL_Quit();
	return 0;
}
```

Patch Notes:
- THE WARNINGS, OH GOD THE WARNINGS
- A good amount of this can be guarded with `__cplusplus`, but not quite all... it might be better to replicate _exactly_ how the official headers do things.
- I mostly improvised some of the interface-y bits from how I remember it working but there's no way it isn't wrong.

Fixes #4

2022-03-12 05:52 UTC, flibitijibibo commented
Fixed the dxvk build, this is "ready" to review.

2022-03-17 15:07 UTC, flibitijibibo commented
Figured out the last of the Win32 quirks, this is now _actually_ ready for review.

2022-04-17 12:59 UTC, Joshua-Ashton requested changes

2022-04-17 12:59 UTC, Joshua-Ashton commented on include/native/windows/windows_base.h
> +#define E_INVALIDARG  0x80070057
These should probably `#define THING ((HRESULT)value)`

2022-04-17 12:59 UTC, Joshua-Ashton commented on include/native/windows/windows_base.h
> +#define FAILED(hr) (hr < 0)
May as well just stick with this everywhere...

2022-04-17 13:14 UTC, flibitijibibo commented
Pushed with both fixes applied! A notable change is that `FAILED`/`SUCCEEDED` needed to wrap `(hr)` for complete safety.

2022-04-19 16:13 UTC, merged